require('dotenv').config();
const express=require('express'), cookieParser=require('cookie-parser'), jwt=require('jsonwebtoken'), bcrypt=require('bcryptjs');
const {createClient}=require('@supabase/supabase-js');
const app=express(); app.use(express.json({limit:'1mb'})); app.use(cookieParser()); app.use(express.static('public'));
const db=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const SECRET=process.env.JWT_SECRET, PRICE=Number(process.env.SUBSCRIPTION_PRICE||600), PAYNO=process.env.PAYMENT_NUMBER||'0736501740';
const phone=v=>String(v||'').replace(/\\s+/g,'').replace(/^\\+254/,'0');
const safe=u=>({id:u.id,email:u.email,phone:u.phone,role:u.role,subscription_status:u.subscription_status,created_at:u.created_at});
function session(res,u){res.cookie('medstudy_session',jwt.sign({sub:u.id,role:u.role},SECRET,{expiresIn:'7d'}),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});}
async function user(req){try{let t=req.cookies.medstudy_session;if(!t)return null;let p=jwt.verify(t,SECRET);let {data}=await db.from('app_users').select('id,email,phone,role,subscription_status,created_at').eq('id',p.sub).single();return data||null}catch{return null}}
const auth=async(req,res,next)=>{req.user=await user(req);if(!req.user)return res.status(401).json({error:'Sign in required'});next()};
const admin=async(req,res,next)=>{req.user=await user(req);if(!req.user||req.user.role!=='developer')return res.status(403).json({error:'Developer access only'});next()};
const access=async(req,res,next)=>{req.user=await user(req);if(!req.user)return res.status(401).json({error:'Sign in required'});if(req.user.role!=='developer'&&req.user.subscription_status!=='active')return res.status(402).json({error:'Active KSh 600 subscription required'});next()};
app.get('/api/config',(q,s)=>s.json({price:PRICE,paymentNumber:PAYNO}));
app.post('/api/auth/signup',async(req,res)=>{let email=String(req.body.email||'').trim().toLowerCase()||null,ph=phone(req.body.phone)||null,p=String(req.body.password||'');if(!email&&!ph)return res.status(400).json({error:'Email or phone required'});if(p.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});let filters=[];if(email)filters.push('email.eq.'+email);if(ph)filters.push('phone.eq.'+ph);let q=await db.from('app_users').select('id').or(filters.join(','));if(q.data&&q.data.length)return res.status(409).json({error:'Account already exists'});let h=await bcrypt.hash(p,12),r=await db.from('app_users').insert({email,phone:ph,password_hash:h}).select('id,email,phone,role,subscription_status,created_at').single();if(r.error)return res.status(500).json({error:r.error.message});session(res,r.data);res.json({user:r.data})});
app.post('/api/auth/login',async(req,res)=>{let id=String(req.body.identity||'').trim(),em=id.toLowerCase(),ph=phone(id),filters=['email.eq.'+em,'phone.eq.'+ph],q=await db.from('app_users').select('*').or(filters.join(',')).limit(1).maybeSingle();if(q.error||!q.data||!(await bcrypt.compare(String(req.body.password||''),q.data.password_hash)))return res.status(401).json({error:'Incorrect sign-in details'});session(res,q.data);res.json({user:safe(q.data)})});
app.post('/api/auth/logout',(q,s)=>{s.clearCookie('medstudy_session');s.json({ok:true})});
app.get('/api/me',async(q,s)=>s.json({user:await user(q)}));
app.get('/api/topics',async(q,s)=>{let r=await db.from('anatomy_topics').select('*').order('sort_order');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{topics:r.data})});
app.get('/api/resources',access,async(q,s)=>{let r=await db.from('resources').select('*').order('created_at');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{resources:r.data})});
app.post('/api/payments',auth,async(req,res)=>{if(req.user.role==='developer')return res.json({status:'active'});let code=String(req.body.mpesaCode||'').trim().toUpperCase();if(!/^[A-Z0-9]{8,20}$/.test(code))return res.status(400).json({error:'Enter your M-Pesa transaction code'});let x=await db.from('payments').select('id').eq('mpesa_code',code).maybeSingle();if(x.data)return res.status(409).json({error:'Code already submitted'});let r=await db.from('payments').insert({user_id:req.user.id,amount:PRICE,payment_number:PAYNO,mpesa_code:code}).select('id,status').single();if(r.error)return res.status(500).json({error:r.error.message});await db.from('app_users').update({subscription_status:'pending'}).eq('id',req.user.id);res.json({payment:r.data})});
app.get('/api/admin/payments',admin,async(q,s)=>{let r=await db.from('payments').select('id,user_id,amount,payment_number,mpesa_code,status,created_at,verified_at,verified_by').order('created_at',{ascending:false});if(r.error)return s.status(500).json({error:r.error.message});let ids=[...new Set((r.data||[]).map(x=>x.user_id).filter(Boolean))];let users=ids.length?await db.from('app_users').select('id,email,phone').in('id',ids):{data:[],error:null};if(users.error)return s.status(500).json({error:users.error.message});let byId=Object.fromEntries((users.data||[]).map(u=>[u.id,{email:u.email,phone:u.phone}]));s.json({payments:(r.data||[]).map(x=>({...x,app_users:byId[x.user_id]||null}))})});
app.post('/api/admin/payments/:id/:action',admin,async(req,res)=>{let action=req.params.action;if(!['approve','reject'].includes(action))return res.status(400).json({error:'Invalid action'});let p=await db.from('payments').select('*').eq('id',req.params.id).single();if(p.error)return res.status(404).json({error:'Payment not found'});await db.from('payments').update({status:action==='approve'?'approved':'rejected',verified_at:new Date().toISOString(),verified_by:req.user.id}).eq('id',p.data.id);await db.from('app_users').update({subscription_status:action==='approve'?'active':'locked'}).eq('id',p.data.user_id);res.json({ok:true})});
app.post('/api/admin/topics',admin,async(req,res)=>{let name=String(req.body.name||'').trim(),group=String(req.body.group_name||'General anatomy').trim();if(!name)return res.status(400).json({error:'Name required'});let r=await db.from('anatomy_topics').insert({name,group_name:group}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{topic:r.data})});
app.post('/api/admin/resources',admin,async(req,res)=>{let b=req.body,r=await db.from('resources').insert({kind:b.kind||'video',title:String(b.title||'').trim(),subject:String(b.subject||'Anatomy').trim(),topic:String(b.topic||'').trim(),url:b.url||null,page:b.page||null,created_by:req.user.id}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{resource:r.data})});
async function ensureAdmin(){let e=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase(),p=String(process.env.ADMIN_PASSWORD||'');if(!e||!p)return;let q=await db.from('app_users').select('id').eq('email',e).maybeSingle();let h=await bcrypt.hash(p,12);if(q.data)await db.from('app_users').update({password_hash:h,role:'developer',subscription_status:'active'}).eq('id',q.data.id);else await db.from('app_users').insert({email:e,password_hash:h,role:'developer',subscription_status:'active'})}
app.use((q,s)=>s.sendFile(require('path').join(__dirname,'public','index.html')));
ensureAdmin().finally(()=>app.listen(Number(process.env.PORT||3000),()=>console.log('MedStudy running')));
