require('dotenv').config();
const express=require('express'),cookieParser=require('cookie-parser'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs'),path=require('path');
const {createClient}=require('@supabase/supabase-js');
const crypto=require('crypto');
const multer=require('multer');
const app=express();
app.use(express.json({limit:'60mb'})); app.use(cookieParser()); app.use(express.static('public'));
const db=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const SECRET=process.env.JWT_SECRET, PRICE=Number(process.env.SUBSCRIPTION_PRICE||600), PAYNO=process.env.PAYMENT_NUMBER||'0736501740';
const OPENAI_KEY=process.env.OPENAI_API_KEY||'', GEMINI_KEY=process.env.GEMINI_API_KEY||'', AI_MODEL=process.env.GEMINI_MODEL||'gemini-3.5-flash-lite', AI_FALLBACK_MODEL=process.env.GEMINI_FALLBACK_MODEL||'gemini-3.6-flash', YT_KEY=process.env.YOUTUBE_API_KEY||'';
const WHATSAPP_TOKEN=process.env.WHATSAPP_ACCESS_TOKEN||'', WHATSAPP_PHONE_ID=process.env.WHATSAPP_PHONE_NUMBER_ID||'', WHATSAPP_TO=String(process.env.WHATSAPP_ADMIN_TO||'').replace(/\s+/g,'').replace(/^\+254/,'254').replace(/^0/,'254'), WHATSAPP_API_VERSION=process.env.WHATSAPP_API_VERSION||'v25.0', WHATSAPP_TEMPLATE=process.env.WHATSAPP_TEMPLATE_NAME||'medstudy_subscription_pending', WHATSAPP_TEMPLATE_LANG=process.env.WHATSAPP_TEMPLATE_LANG||'en_US';
const TELEGRAM_TOKEN=process.env.TELEGRAM_BOT_TOKEN||'', TELEGRAM_CHAT_ID=String(process.env.TELEGRAM_CHAT_ID||'').trim();
const phone=v=>String(v||'').replace(/\s+/g,'').replace(/^\+254/,'0');
const safe=u=>({id:u.id,email:u.email,phone:u.phone,role:u.role,subscription_status:u.subscription_status,subscription_started_at:u.subscription_started_at,subscription_ends_at:u.subscription_ends_at,created_at:u.created_at});
async function session(res,u,deviceId,req){let did=String(deviceId||'').trim();if(!/^[A-Za-z0-9._:-]{16,200}$/.test(did))throw Error('A valid device identifier is required.');let active=await db.from('device_sessions').select('id,device_id').eq('user_id',u.id).gt('expires_at',new Date().toISOString());if(active.error)throw Error(active.error.message);let same=(active.data||[]).find(x=>x.device_id===did);if(!same&&(active.data||[]).length>=2)throw Error('This account is already active on two devices. Sign out from one device before signing in here.');await db.from('device_sessions').delete().eq('user_id',u.id).eq('device_id',did);let sid=crypto.randomUUID(),expiresAt=new Date(Date.now()+604800000).toISOString();let ins=await db.from('device_sessions').insert({id:sid,user_id:u.id,device_id:did,expires_at:expiresAt,user_agent:String(req.headers['user-agent']||'').slice(0,500)});if(ins.error)throw Error(ins.error.message);let token=jwt.sign({sub:u.id,role:u.role,sid},SECRET,{expiresIn:'7d'});res.cookie('medstudy_session',token,{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});}
async function user(req){try{let t=req.cookies.medstudy_session;if(!t)return null;let p=jwt.verify(t,SECRET);if(!p.sid)return null;let sess=await db.from('device_sessions').select('id,user_id,device_id,expires_at').eq('id',p.sid).eq('user_id',p.sub).gt('expires_at',new Date().toISOString()).maybeSingle();if(sess.error||!sess.data)return null;let did=String(req.headers['x-device-id']||'').trim();if(!did||did!==sess.data.device_id)return null;let {data}=await db.from('app_users').select('id,email,phone,role,subscription_status,subscription_started_at,subscription_ends_at,created_at').eq('id',p.sub).single();if(!data)return null;if(data.role!=='developer'&&data.subscription_status==='active'&&data.subscription_ends_at&&new Date(data.subscription_ends_at)<=new Date()){await db.from('app_users').update({subscription_status:'locked',updated_at:new Date().toISOString()}).eq('id',data.id);data.subscription_status='locked';}await db.from('device_sessions').update({last_seen_at:new Date().toISOString()}).eq('id',p.sid);return data}catch{return null}}
const auth=async(req,res,next)=>{req.user=await user(req);if(!req.user)return res.status(401).json({error:'Sign in required'});next()};
const access=async(req,res,next)=>{req.user=await user(req);if(!req.user)return res.status(401).json({error:'Sign in required'});if(req.user.role!=='developer'&&(req.user.subscription_status!=='active'||!req.user.subscription_ends_at||new Date(req.user.subscription_ends_at)<=new Date()))return res.status(402).json({error:'Your subscription has expired. Please renew your KSh 600 subscription.'});next()};
const admin=async(req,res,next)=>{req.user=await user(req);if(!req.user||req.user.role!=='developer')return res.status(403).json({error:'Developer access only'});next()};
app.get('/api/config',(q,s)=>s.json({price:PRICE,paymentNumber:PAYNO,aiConfigured:!!GEMINI_KEY,aiProvider:'Gemini free tier',aiModel:AI_MODEL,youtubeSearchConfigured:!!YT_KEY,whatsappConfigured:!!(WHATSAPP_TOKEN&&WHATSAPP_PHONE_ID&&WHATSAPP_TO),telegramConfigured:!!(TELEGRAM_TOKEN&&TELEGRAM_CHAT_ID)}));
app.post('/api/auth/signup',async(req,res)=>{let email=String(req.body.email||'').trim().toLowerCase()||null,ph=phone(req.body.phone)||null,p=String(req.body.password||'');if(!email&&!ph)return res.status(400).json({error:'Email or phone required'});if(p.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});let filters=[];if(email)filters.push('email.eq.'+email);if(ph)filters.push('phone.eq.'+ph);let q=await db.from('app_users').select('id').or(filters.join(','));if(q.data&&q.data.length)return res.status(409).json({error:'Account already exists'});let h=await bcrypt.hash(p,12),r=await db.from('app_users').insert({email,phone:ph,password_hash:h}).select('id,email,phone,role,subscription_status,subscription_started_at,subscription_ends_at,created_at').single();if(r.error)return res.status(500).json({error:r.error.message});try{await session(res,r.data,req.headers['x-device-id'],req)}catch(e){await db.from('app_users').delete().eq('id',r.data.id);return res.status(409).json({error:e.message})}res.json({user:safe(r.data)})});
app.post('/api/auth/login',async(req,res)=>{let id=String(req.body.identity||'').trim(),em=id.toLowerCase(),ph=phone(id),filters=['email.eq.'+em,'phone.eq.'+ph],q=await db.from('app_users').select('*').or(filters.join(',')).limit(1).maybeSingle();if(q.error||!q.data||!(await bcrypt.compare(String(req.body.password||''),q.data.password_hash)))return res.status(401).json({error:'Incorrect sign-in details'});if(q.data.role!=='developer'&&q.data.subscription_status==='active'&&q.data.subscription_ends_at&&new Date(q.data.subscription_ends_at)<=new Date()){await db.from('app_users').update({subscription_status:'locked',updated_at:new Date().toISOString()}).eq('id',q.data.id);q.data.subscription_status='locked'}try{await session(res,q.data,req.headers['x-device-id'],req)}catch(e){return res.status(409).json({error:e.message})}res.json({user:safe(q.data)})});
app.post('/api/auth/logout',async(q,s)=>{try{let t=q.cookies.medstudy_session;if(t){let p=jwt.verify(t,SECRET);if(p.sid)await db.from('device_sessions').delete().eq('id',p.sid)}}catch{}s.clearCookie('medstudy_session');s.json({ok:true})});
app.get('/api/me',async(q,s)=>s.json({user:await user(q)}));
app.get('/api/learner/preferences',auth,async(req,res)=>{let r=await db.from('learner_preferences').select('*').eq('user_id',req.user.id).maybeSingle();if(r.error)return res.status(500).json({error:r.error.message});if(!r.data){let x=await db.from('learner_preferences').insert({user_id:req.user.id}).select('*').single();return res.json({preferences:x.data})}res.json({preferences:r.data})});
app.post('/api/learner/preferences',auth,async(req,res)=>{let b=req.body,p={user_id:req.user.id,pace:String(b.pace||'balanced'),explanation_depth:String(b.explanation_depth||'moderate'),question_style:String(b.question_style||'mixed'),daily_goal_minutes:Math.max(5,Math.min(240,Number(b.daily_goal_minutes||30))),preferred_subjects:Array.isArray(b.preferred_subjects)?b.preferred_subjects:[],weak_topics:Array.isArray(b.weak_topics)?b.weak_topics:[],updated_at:new Date().toISOString()};let r=await db.from('learner_preferences').upsert(p,{onConflict:'user_id'}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{preferences:r.data})});
app.post('/api/ai/chat',access,async(req,res)=>{if(!GEMINI_KEY)return res.status(503).json({error:'Student AI tutor is not configured yet. Add a Gemini API key to the Railway service as GEMINI_API_KEY.'});let message=String(req.body.message||'').trim();if(!message)return res.status(400).json({error:'Message required'});let pref=await db.from('learner_preferences').select('*').eq('user_id',req.user.id).maybeSingle();let recent=await db.from('ai_chat_messages').select('role,content').eq('user_id',req.user.id).order('created_at',{ascending:false}).limit(12);let context='Learner preferences: '+JSON.stringify(pref.data||{})+'\\nRecent conversation: '+JSON.stringify((recent.data||[]).reverse());let resource=null;if(req.body.resourceId){let rr=await db.from('resources').select('id,title,subject,topic').eq('id',req.body.resourceId).maybeSingle();resource=rr.data||null}let system='You are MedStudy Space Learner Helper, a patient medical-study coach. Tailor explanations to the learner preferences. Teach, question, correct and encourage without doing the learner work for them. If a source resource is supplied, stay grounded in that resource and clearly say when information is outside it. Prefer concise explanations, clinical/anatomical examples when useful, active recall, and spaced review. Never claim certainty when the source is unclear. '+context+(resource?'\\nCurrent resource: '+JSON.stringify(resource):'');try{let answer=await ai(system+'\\n\\nSTUDENT MESSAGE:\\n'+message);await db.from('ai_chat_messages').insert([{user_id:req.user.id,resource_id:req.body.resourceId||null,role:'user',content:message},{user_id:req.user.id,resource_id:req.body.resourceId||null,role:'assistant',content:answer}]);await db.from('study_activity').insert({user_id:req.user.id,resource_id:req.body.resourceId||null,activity_type:'tutor_chat',metadata:{adaptive:true,provider:'gemini'}});res.json({answer})}catch(e){res.status(502).json({error:e.message})}});
app.get('/api/youtube/search',access,async(req,res)=>{if(!YT_KEY)return res.status(503).json({error:'YouTube search is not configured yet. Please add a YouTube Data API key in Railway.'});let q=String(req.query.q||'').trim();if(q.length<2)return res.status(400).json({error:'Enter at least 2 characters'});try{let uu=new URL('https://www.googleapis.com/youtube/v3/search');uu.searchParams.set('part','snippet');uu.searchParams.set('q',q);uu.searchParams.set('type','video');uu.searchParams.set('maxResults','20');uu.searchParams.set('regionCode','KE');uu.searchParams.set('key',YT_KEY);let rr=await fetch(uu);let dd=await rr.json().catch(()=>({}));if(!rr.ok){console.error('YouTube search HTTP '+rr.status,JSON.stringify(dd));return res.status(502).json({error:dd.error?.message||'YouTube search failed. Check that YouTube Data API v3 is enabled for the API key.'})}let items=(dd.items||[]).filter(x=>x.id?.videoId);res.json({results:items.map(x=>({id:x.id.videoId,title:x.snippet.title,channel:x.snippet.channelTitle,description:x.snippet.description,thumbnail:x.snippet.thumbnails?.medium?.url,url:'https://www.youtube.com/watch?v='+x.id.videoId,embeddable:true}))})}catch(err){console.error('YouTube search exception:',err.message);res.status(502).json({error:'YouTube search is temporarily unavailable. Please try again.'})}});
app.get('/api/topics',async(q,s)=>{let r=await db.from('anatomy_topics').select('*').order('sort_order');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{topics:r.data})});
app.get('/api/subjects',async(q,s)=>{let r=await db.from('subjects').select('*').order('sort_order').order('name');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{subjects:r.data})});
app.get('/api/subjects/:id/topics',async(q,s)=>{let r=await db.from('subject_topics').select('*').eq('subject_id',q.params.id).order('sort_order').order('name');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{topics:r.data})});
app.get('/api/books',access,async(q,s)=>{let r=await db.from('book_references').select('*').order('title');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{books:r.data})});

app.get('/api/resources',access,async(q,s)=>{let r=await db.from('resources').select('*').order('subject').order('topic').order('created_at');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{resources:r.data})});
app.get('/api/resources/:id',access,async(req,res)=>{let r=await db.from('resources').select('*').eq('id',req.params.id).single();if(r.error)return res.status(404).json({error:'Lecture not found'});res.json({resource:r.data})});
async function notifyWhatsAppPending(p,user){if(!WHATSAPP_TOKEN||!WHATSAPP_PHONE_ID||!WHATSAPP_TO)return {ok:false,skipped:true};try{let endpoint='https://graph.facebook.com/'+WHATSAPP_API_VERSION+'/'+encodeURIComponent(WHATSAPP_PHONE_ID)+'/messages';let body={messaging_product:'whatsapp',to:WHATSAPP_TO,type:'template',template:{name:WHATSAPP_TEMPLATE,language:{code:WHATSAPP_TEMPLATE_LANG},components:[{type:'body',parameters:[{type:'text',text:String(user.email||user.phone||user.id)},{type:'text',text:String(user.phone||'')},{type:'text',text:'KSh '+PRICE},{type:'text',text:String(p.mpesa_code||'')}]}]}};let r=await fetch(endpoint,{method:'POST',headers:{Authorization:'Bearer '+WHATSAPP_TOKEN,'Content-Type':'application/json'},body:JSON.stringify(body)});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error?.message||'WhatsApp notification failed');return {ok:true,id:d.messages?.[0]?.id||null}}catch(e){console.error('WhatsApp pending notification:',e.message);return {ok:false,error:e.message}}}
async function notifyTelegramPending(p,user){
  if(!TELEGRAM_TOKEN||!TELEGRAM_CHAT_ID)return {ok:false,skipped:true};
  try{
    let text='🔔 New MedStudy Space payment\\n\\nStudent: '+(user.email||user.phone||user.id)+'\\nPhone: '+(user.phone||'')+'\\nAmount: KSh '+PRICE+'\\nM-Pesa code: '+(p.mpesa_code||'')+'\\n\\nOpen the Admin panel to approve or reject.';
    let r=await fetch('https://api.telegram.org/bot'+encodeURIComponent(TELEGRAM_TOKEN)+'/sendMessage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:TELEGRAM_CHAT_ID,text})});
    let d=await r.json().catch(()=>({}));
    if(!r.ok||!d.ok)throw Error(d.description||'Telegram notification failed');
    return {ok:true,id:d.result?.message_id||null}
  }catch(e){console.error('Telegram pending notification:',e.message);return {ok:false,error:e.message}}
}
app.post('/api/payments',auth,async(req,res)=>{if(req.user.role==='developer')return res.json({status:'active'});let code=String(req.body.mpesaCode||'').trim().toUpperCase();if(!/^[A-Z0-9]{8,20}$/.test(code))return res.status(400).json({error:'Enter your M-Pesa transaction code'});let x=await db.from('payments').select('id').eq('mpesa_code',code).maybeSingle();if(x.data)return res.status(409).json({error:'Code already submitted'});let r=await db.from('payments').insert({user_id:req.user.id,amount:PRICE,payment_number:PAYNO,mpesa_code:code}).select('id,status').single();if(r.error)return res.status(500).json({error:r.error.message});await db.from('app_users').update({subscription_status:'pending'}).eq('id',req.user.id);let wa=await notifyWhatsAppPending({mpesa_code:code},req.user);let tg=await notifyTelegramPending({mpesa_code:code},req.user);let whatsappLink=WHATSAPP_TO?'https://wa.me/'+WHATSAPP_TO+'?text='+encodeURIComponent('MedStudy Space payment pending%0AStudent: '+(req.user.email||req.user.phone||req.user.id)+'%0APhone: '+(req.user.phone||'')+'%0AAmount: KSh '+PRICE+'%0AM-Pesa code: '+code):null;res.json({payment:r.data,whatsappNotification:wa.ok?'sent':'not_sent',telegramNotification:tg.ok?'sent':'not_sent',whatsappLink})});
app.get('/api/admin/payments',admin,async(q,s)=>{let r=await db.from('payments').select('id,user_id,amount,payment_number,mpesa_code,status,created_at,verified_at,verified_by').order('created_at',{ascending:false});if(r.error)return s.status(500).json({error:r.error.message});let ids=[...new Set((r.data||[]).map(x=>x.user_id).filter(Boolean))];let users=ids.length?await db.from('app_users').select('id,email,phone,subscription_status,subscription_started_at,subscription_ends_at').in('id',ids):{data:[],error:null};if(users.error)return s.status(500).json({error:users.error.message});let byId=Object.fromEntries((users.data||[]).map(u=>[u.id,{email:u.email,phone:u.phone}]));s.json({payments:(r.data||[]).map(x=>({...x,app_users:byId[x.user_id]||null}))})});
app.post('/api/admin/payments/:id/:action',admin,async(req,res)=>{let action=req.params.action;if(!['approve','reject'].includes(action))return res.status(400).json({error:'Invalid action'});let p=await db.from('payments').select('*').eq('id',req.params.id).single();if(p.error)return res.status(404).json({error:'Payment not found'});let verifiedAt=new Date().toISOString();await db.from('payments').update({status:action==='approve'?'approved':'rejected',verified_at:verifiedAt,verified_by:req.user.id}).eq('id',p.data.id);if(action==='approve'){let d=new Date(verifiedAt);d.setMonth(d.getMonth()+6);await db.from('app_users').update({subscription_status:'active',subscription_started_at:verifiedAt,subscription_ends_at:d.toISOString(),updated_at:verifiedAt}).eq('id',p.data.user_id)}else{await db.from('app_users').update({subscription_status:'locked',updated_at:verifiedAt}).eq('id',p.data.user_id)}res.json({ok:true})});
app.post('/api/admin/subjects',admin,async(req,res)=>{let name=String(req.body.name||'').trim(),description=String(req.body.description||'').trim();if(!name)return res.status(400).json({error:'Subject name required'});let r=await db.from('subjects').insert({name,description}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{subject:r.data})});
app.post('/api/admin/subjects/:id/topics',admin,async(req,res)=>{let name=String(req.body.name||'').trim();if(!name)return res.status(400).json({error:'Topic name required'});let r=await db.from('subject_topics').insert({subject_id:req.params.id,name}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{topic:r.data})});
app.post('/api/admin/books',admin,async(req,res)=>{let b=req.body,title=String(b.title||'').trim(),url=String(b.url||'').trim();if(!title||!url)return res.status(400).json({error:'Book title and URL are required'});let r=await db.from('book_references').insert({title,authors:String(b.authors||'').trim()||null,edition:String(b.edition||'').trim()||null,url,notes:String(b.notes||'').trim()||null,subject_id:b.subject_id||null,topic_id:b.topic_id||null,created_by:req.user.id}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{book:r.data})});
app.post('/api/admin/topics',admin,async(req,res)=>{let name=String(req.body.name||'').trim(),group=String(req.body.group_name||'General anatomy').trim();if(!name)return res.status(400).json({error:'Name required'});let r=await db.from('anatomy_topics').insert({name,group_name:group}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{topic:r.data})});
app.post('/api/admin/resources',admin,async(req,res)=>{let b=req.body,title=String(b.title||'').trim(),url=String(b.url||'').trim();if(!title||!url)return res.status(400).json({error:'Title and URL are required'});let r=await db.from('resources').insert({kind:b.kind||'video',title,subject:String(b.subject||'Anatomy').trim(),topic:String(b.topic||'General anatomy').trim(),subject_id:b.subject_id||null,topic_id:b.topic_id||null,description:String(b.description||'').trim()||null,url,page:b.page||null,created_by:req.user.id}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{resource:r.data})});
async function ensureStorage(){try{let x=await db.storage.getBucket('medstudy-resources');let opts={public:false,fileSizeLimit:'100MB',allowedMimeTypes:['application/pdf','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.oasis.opendocument.presentation','text/plain','audio/mpeg','audio/mp4','audio/wav','audio/x-m4a']};if(x.error)await db.storage.createBucket('medstudy-resources',opts);else await db.storage.updateBucket('medstudy-resources',opts)}catch(e){console.error('Storage setup:',e.message)}}
function safeName(v){return String(v||'file').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(0,120)}
app.post('/api/admin/resources/upload',admin,async(req,res)=>{let b=req.body,title=String(b.title||'').trim(),mime=String(b.mimeType||''),base=String(b.fileBase64||'').replace(/^data:[^,]+,/,'');if(!title||!mime||!base)return res.status(400).json({error:'Title, file type and file are required'});let allowed=['application/pdf','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.oasis.opendocument.presentation'];if(!allowed.includes(mime))return res.status(400).json({error:'Only PDF, PPT, PPTX or ODP lecture files are supported'});let buf;try{buf=Buffer.from(base,'base64')}catch{return res.status(400).json({error:'Invalid file data'})}if(buf.length>40*1024*1024)return res.status(413).json({error:'File is too large. Maximum is 40 MB on this setup.'});let sid=b.subject_id||null,tid=b.topic_id||null,sub= sid?await db.from('subjects').select('name').eq('id',sid).single():{data:null},top=tid?await db.from('subject_topics').select('name').eq('id',tid).single():{data:null};let resource=await db.from('resources').insert({kind:'slides',title,subject:sub.data?.name||String(b.subject||'General'),topic:top.data?.name||String(b.topic||'General'),subject_id:sid,topic_id:tid,description:String(b.description||'').trim()||null,created_by:req.user.id}).select('*').single();if(resource.error)return res.status(400).json({error:resource.error.message});let pathKey='resources/'+resource.data.id+'/'+crypto.randomUUID()+'-'+safeName(b.fileName||'lecture.pdf');let up=await db.storage.from('medstudy-resources').upload(pathKey,buf,{contentType:mime,upsert:false});if(up.error){await db.from('resources').delete().eq('id',resource.data.id);return res.status(400).json({error:up.error.message})}let rf=await db.from('resource_files').insert({resource_id:resource.data.id,subject_id:sid,topic_id:tid,title,storage_path:pathKey,mime_type:mime,size_bytes:buf.length,created_by:req.user.id}).select('*').single();if(rf.error){await db.storage.from('medstudy-resources').remove([pathKey]);await db.from('resources').delete().eq('id',resource.data.id);return res.status(400).json({error:rf.error.message})}res.json({resource:resource.data,file:rf.data})});
const zipUpload=multer({storage:multer.memoryStorage(),limits:{fileSize:260*1024*1024}});
function importSubjectName(root,path){let r=String(root||'').toUpperCase();if(r==='BIOCHEMISTRY')return 'Biochemistry';if(r==='BEHAVIOURAL SCIENCE'||r==='BEHAVIORAL SCIENCE')return 'Behavioral Science';if(r==='DR BEDA SLIDES')return 'Anatomy';if(r==='MODULES')return /SOCIAL AND BEHAVIOURAL|SOCIAL AND BEHAVIORAL|BEHAVIOUR|BEHAVIOR|PSYCH|HEALTHCARE|ANTHROPOLOGY|SOCIOLOGY/i.test(path)?'Behavioral Science':'Behavioral Science';return null}
async function ensureImportTopic(subjectName,topicName){let s=await db.from('subjects').select('id').eq('name',subjectName).maybeSingle();if(s.error)throw Error(s.error.message);let sid=s.data?.id;if(!sid){let ins=await db.from('subjects').insert({name:subjectName,description:'Imported course content.',sort_order:90}).select('id').single();if(ins.error)throw Error(ins.error.message);sid=ins.data.id}let clean=String(topicName||'General').replace(/\\+/g,'/').split('/').filter(Boolean).pop()||'General';let t=await db.from('subject_topics').select('id').eq('subject_id',sid).eq('name',clean).maybeSingle();if(t.error)throw Error(t.error.message);if(t.data)return {sid,tid:t.data.id,name:clean};let ins=await db.from('subject_topics').insert({subject_id:sid,name:clean}).select('id').single();if(ins.error)throw Error(ins.error.message);return {sid,tid:ins.data.id,name:clean}}
async function importZipFile(req,res){if(!req.file)return res.status(400).json({error:'ZIP file is required'});let archive;try{archive=await unzipper.Open.buffer(req.file.buffer)}catch(e){return res.status(400).json({error:'The uploaded ZIP could not be opened: '+e.message})}let imported=0,skipped=0,errors=[];for(const entry of archive.files){let path=String(entry.path||'').replace(/^\\/,'');if(entry.type!=='File'||!path||path.startsWith('__MACOSX/')||path.includes('/.')){skipped++;continue}let ext=path.toLowerCase().split('.').pop();let mimeMap={pdf:'application/pdf',ppt:'application/vnd.ms-powerpoint',pptx:'application/vnd.openxmlformats-officedocument.presentationml.presentation',odp:'application/vnd.oasis.opendocument.presentation'};if(!mimeMap[ext]){skipped++;continue}if(entry.uncompressedSize>100*1024*1024){errors.push(path+': file exceeds 100 MB');continue}let parts=path.split('/').filter(Boolean);let subject=importSubjectName(parts[0],path);if(!subject){skipped++;continue}let topic=parts.length>2?parts[1]:'General';let title=parts[parts.length-1].replace(/\\.[^.]+$/,'');try{let loc=await ensureImportTopic(subject,topic);let exists=await db.from('resources').select('id').eq('title',title).eq('subject',subject).eq('topic',loc.name).maybeSingle();if(exists.error)throw Error(exists.error.message);if(exists.data){skipped++;continue}let buf=await entry.buffer();let resource=await db.from('resources').insert({kind:'slides',title,subject,topic:loc.name,subject_id:loc.sid,topic_id:loc.tid,description:'Imported from '+req.file.originalname,created_by:req.user.id}).select('*').single();if(resource.error)throw Error(resource.error.message);let pathKey='resources/'+resource.data.id+'/'+crypto.randomUUID()+'-'+safeName(parts[parts.length-1]);let up=await db.storage.from('medstudy-resources').upload(pathKey,buf,{contentType:mimeMap[ext],upsert:false});if(up.error){await db.from('resources').delete().eq('id',resource.data.id);throw Error(up.error.message)}let rf=await db.from('resource_files').insert({resource_id:resource.data.id,subject_id:loc.sid,topic_id:loc.tid,title,storage_path:pathKey,mime_type:mimeMap[ext],size_bytes:buf.length,created_by:req.user.id}).select('*').single();if(rf.error){await db.storage.from('medstudy-resources').remove([pathKey]);await db.from('resources').delete().eq('id',resource.data.id);throw Error(rf.error.message)}if(ext==='pdf'){try{let parsed=await (await import('pdf-parse')).default(buf);if(parsed.text?.trim())await db.from('lecture_transcripts').insert({resource_id:resource.data.id,source:'imported-pdf',language:'en',transcript:parsed.text.trim()})}catch(e){errors.push(title+': PDF stored but text extraction failed')}}imported++}catch(e){errors.push(path+': '+e.message)}}res.json({ok:true,source:req.file.originalname,imported,skipped,errors})}
app.post('/api/admin/import-zip',admin,zipUpload.single('zip'),importZipFile);
app.get('/api/resources/:id/file-url',access,async(req,res)=>{let f=await db.from('resource_files').select('*').eq('resource_id',req.params.id).maybeSingle();if(f.error||!f.data)return res.status(404).json({error:'File not found'});let u=await db.storage.from('medstudy-resources').createSignedUrl(f.data.storage_path,3600);if(u.error)return res.status(500).json({error:u.error.message});res.json({url:u.data.signedUrl,file:f.data})});
function youtubeId(url){try{let u=new URL(url);if(u.hostname==='youtu.be')return u.pathname.slice(1);if(u.hostname.includes('youtube.com')){if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2];if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2];return u.searchParams.get('v')}}catch{}return null}
async function fetchTranscript(url){let id=youtubeId(url);if(!id)throw Error('This lecture does not have a supported YouTube video URL.');try{const mod=await import('youtube-transcript-plus');const result=await mod.fetchTranscript(id);let text=result.map(x=>x.text).join(' ').replace(/\s+/g,' ').trim();if(!text)throw Error('No transcript was returned.');return {text,language:'en'};}catch(e){throw Error('Could not fetch a YouTube transcript. The video may have captions disabled, or YouTube may be blocking transcript requests from the server. You can add a transcript manually from the developer dashboard.');}}
async function geminiYouTubeTranscript(url){
  if(!GEMINI_KEY)throw Error('AI is not configured. Add GEMINI_API_KEY to the Railway service variables.');
  let id=youtubeId(url);
  if(!id)throw Error('Paste a valid public YouTube video link.');
  let youtubeUrl='https://www.youtube.com/watch?v='+encodeURIComponent(id);
  let prompt='Create an accurate transcript of the spoken content in this public YouTube lecture. Preserve important medical terminology, punctuation and useful timestamps when available. Do not summarize or invent content. If a word is genuinely unclear, write [unclear]. Return only the transcript.';
  let models=['gemini-3.8-flash','gemini-3.7-flash','gemini-3.6-flash','gemini-3.5-flash-lite','gemini-3.5-flash',AI_MODEL,AI_FALLBACK_MODEL].filter((x,i,a)=>x&&a.indexOf(x)===i);
  let last='Gemini could not process this YouTube video.';
  for(const model of models){
    for(let attempt=0;attempt<2;attempt++){
      try{
        let rr=await fetch('https://generativelanguage.googleapis.com/v1beta/interactions',{
          method:'POST',
          headers:{'Content-Type':'application/json','x-goog-api-key':GEMINI_KEY},
          body:JSON.stringify({
            model,
            input:[
              {type:'video',uri:youtubeUrl},
              {type:'text',text:prompt}
            ]
          })
        });
        let dd=await rr.json().catch(()=>({}));
        if(rr.ok){
          let text=String(dd.output_text||extractText(dd.candidates?.[0]?.content||dd)).trim();
          if(text.length>=50)return {text,model};
          last='Gemini returned an empty or very short transcript.';
          break;
        }
        last=dd.error?.message||('Gemini returned HTTP '+rr.status);
        console.error('Gemini YouTube HTTP '+rr.status+' using '+model+' attempt '+(attempt+1)+': '+last);
        if(rr.status===400||rr.status===401||rr.status===403||rr.status===404)break;
        if(rr.status!==429&&rr.status!==500&&rr.status!==502&&rr.status!==503&&rr.status!==504)break;
        await new Promise(r=>setTimeout(r,1500*(attempt+1)));
      }catch(e){
        last=e.message;
        console.error('Gemini YouTube '+model+' attempt '+(attempt+1)+': '+e.message);
        await new Promise(r=>setTimeout(r,1500*(attempt+1)));
      }
    }
  }
  throw Error(last);
}
async function ai(prompt){if(!GEMINI_KEY)throw Error('Student AI tutor is not configured yet. Add GEMINI_API_KEY to the Railway service variables.');let models=[AI_MODEL,AI_FALLBACK_MODEL,'gemini-3.5-flash'].filter((x,i,a)=>x&&a.indexOf(x)===i),last='Gemini AI request failed';for(const model of models){for(let attempt=0;attempt<2;attempt++){try{let rr=await fetch('https://generativelanguage.googleapis.com/v1beta/models/'+encodeURIComponent(model)+':generateContent?key='+encodeURIComponent(GEMINI_KEY),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:String(prompt)}]}]})});let dd=await rr.json().catch(()=>({}));if(rr.ok){let tt=extractText(dd.candidates?.[0]?.content||dd);if(tt)return tt.trim();last='Gemini returned an empty response';break}last=dd.error?.message||('Gemini '+model+' returned HTTP '+rr.status);console.error('Gemini model '+model+' HTTP '+rr.status+': '+last);if(![429,500,502,503,504].includes(rr.status))break}catch(err){last=err.message;console.error('Gemini model '+model+': '+err.message)}if(attempt===0)await new Promise(resolve=>setTimeout(resolve,1000))}}throw Error('Student AI is temporarily busy. Please try again in a few seconds. '+last)}
function cleanJson(t){let x=t.trim().replace(/^\`\`\`(?:json)?/i,'').replace(/\`\`\`$/,'').trim();let a=x.indexOf('{'),b=x.lastIndexOf('}');if(a>=0&&b>a)return x.slice(a,b+1);a=x.indexOf('[');b=x.lastIndexOf(']');if(a>=0&&b>a)return x.slice(a,b+1);return x;}
async function getTranscriptFor(resource,allowManual=true){let c=await db.from('lecture_transcripts').select('*').eq('resource_id',resource.id).maybeSingle();if(c.data)return c.data;if(!allowManual)throw Error('No transcript available for this lecture.');if(resource.kind==='slides'){let f=await db.from('resource_files').select('*').eq('resource_id',resource.id).maybeSingle();if(f.data&&f.data.mime_type==='application/pdf'){let file=await db.storage.from('medstudy-resources').download(f.data.storage_path);if(!file.error){try{const pdfParse=(await import('pdf-parse')).default;let parsed=await pdfParse(file.data);if(parsed.text?.trim()){let r=await db.from('lecture_transcripts').insert({resource_id:resource.id,source:'uploaded-pdf',language:'en',transcript:parsed.text}).select('*').single();if(r.error)throw Error(r.error.message);return r.data}}catch(e){throw Error('The PDF was uploaded, but its text could not be extracted: '+e.message)}}}}let tr=await fetchTranscript(resource.url);let r=await db.from('lecture_transcripts').insert({resource_id:resource.id,source:'youtube',language:tr.language,transcript:tr.text}).select('*').single();if(r.error)throw Error(r.error.message);return r.data}
function splitText(text,size=42000){let words=text.split(/\s+/),chunks=[],cur='';for(const w of words){if((cur+' '+w).trim().length>size){chunks.push(cur.trim());cur=w}else cur=(cur+' '+w).trim()}if(cur)chunks.push(cur);return chunks.slice(0,5)}
async function generatePack(resource,transcript){let chunks=splitText(transcript,42000),summaries=[];for(let i=0;i<chunks.length;i++){summaries.push(await ai(`You are an anatomy education assistant. Summarize ONLY the source transcript below. Do not invent facts not supported by it. Preserve anatomical terminology. Produce concise study notes with headings, structures, relations, actions, innervation, blood supply, clinical points, and must-remember facts where the transcript actually covers them.\n\nSOURCE CHUNK ${i+1}/${chunks.length}:\n${chunks[i]}`))}
let combined=summaries.join('\n\n--- CHUNK SUMMARY ---\n');let prompt=`Create a complete study pack for the anatomy lecture titled "${resource.title}". The material below is derived from the lecture transcript. Stay grounded in it and clearly avoid adding unsupported details. Return VALID JSON only with this shape: {"overview":"","objectives":[""],"notes":[{"heading":"","points":[""]}],"key_structures":[""],"clinical_correlations":[""],"must_remember":[""],"summary":"","questions":[{"type":"mcq","question":"","options":["","","",""],"answer":0,"explanation":""}],"flashcards":[{"front":"","back":""}]}. Make 10 useful MCQs, 12 flashcards, and comprehensive notes.\n\nLECTURE MATERIAL:\n${combined}`;let raw=await ai(prompt),pack=JSON.parse(cleanJson(raw));return pack}
app.post('/api/resources/:id/ai/generate',access,async(req,res)=>{let rr=await db.from('resources').select('*').eq('id',req.params.id).single();if(rr.error)return res.status(404).json({error:'Lecture not found'});try{let tr=await getTranscriptFor(rr.data),pack=await generatePack(rr.data,tr.transcript);let old=await db.from('ai_study_packs').select('id').eq('resource_id',rr.data.id).maybeSingle();let r=old.data?await db.from('ai_study_packs').update({notes:pack,questions:pack.questions||[],flashcards:pack.flashcards||[],model:AI_MODEL,updated_at:new Date().toISOString()}).eq('resource_id',rr.data.id).select('*').single():await db.from('ai_study_packs').insert({resource_id:rr.data.id,notes:pack,questions:pack.questions||[],flashcards:pack.flashcards||[],model:AI_MODEL}).select('*').single();if(r.error)throw Error(r.error.message);res.json({pack:r.data})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/resources/:id/ai',access,async(req,res)=>{let r=await db.from('ai_study_packs').select('*').eq('resource_id',req.params.id).maybeSingle();res.json({pack:r.data||null})});
app.post('/api/resources/:id/transcribe-audio',admin,async(req,res)=>{if(!OPENAI_KEY)return res.status(503).json({error:'Voice transcription is not configured. Add OPENAI_API_KEY to the Railway service before using voice transcription.'});let mime=String(req.body.mimeType||''),base=String(req.body.fileBase64||'').replace(/^data:[^,]+,/,'');if(!base)return res.status(400).json({error:'Audio file is required'});let allowed=['audio/mpeg','audio/mp4','audio/wav','audio/x-m4a','audio/webm'];if(!allowed.includes(mime))return res.status(400).json({error:'Use MP3, M4A/MP4, WAV or WebM audio'});let buf=Buffer.from(base,'base64');if(buf.length>25*1024*1024)return res.status(413).json({error:'Audio is too large for this transcription upload. Use a shorter file or split the lecture into parts.'});let fd=new FormData();fd.append('model','gpt-4o-transcribe');fd.append('file',new Blob([buf],{type:mime}),safeName(req.body.fileName||'lecture-audio'));let rr=await fetch('https://api.openai.com/v1/audio/transcriptions',{method:'POST',headers:{Authorization:'Bearer '+OPENAI_KEY},body:fd});let data=await rr.json().catch(()=>({}));if(!rr.ok)return res.status(400).json({error:data.error?.message||'Voice transcription failed'});let text=String(data.text||'').trim();if(text.length<50)return res.status(400).json({error:'The transcription was empty or too short'});let r=await db.from('lecture_transcripts').upsert({resource_id:req.params.id,source:'authorized-audio-asr',language:'en',transcript:text,updated_at:new Date().toISOString()},{onConflict:'resource_id'}).select('*').single();if(r.error)return res.status(400).json({error:r.error.message});res.json({transcript:r.data})});
app.post('/api/resources/:id/transcript',admin,async(req,res)=>{let text=String(req.body.transcript||'').trim();if(text.length<50)return res.status(400).json({error:'Transcript is too short'});let r=await db.from('lecture_transcripts').upsert({resource_id:req.params.id,source:'manual',language:String(req.body.language||'en'),transcript:text,updated_at:new Date().toISOString()},{onConflict:'resource_id'}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{transcript:r.data})});
app.post('/api/resources/:id/tutor',access,async(req,res)=>{let rr=await db.from('resources').select('*').eq('id',req.params.id).single();if(rr.error)return res.status(404).json({error:'Lecture not found'});let tr=await getTranscriptFor(rr.data),question=String(req.body.question||'').trim();if(!question)return res.status(400).json({error:'Ask a question first'});let context=tr.transcript.slice(0,60000);let answer=await ai(`You are a source-grounded anatomy tutor. Answer the student's question using ONLY the lecture transcript below. If the transcript does not support the answer, say that it is not covered in this lecture. Explain clearly at medical-student level and do not fabricate.\n\nQUESTION:\n${question}\n\nLECTURE TRANSCRIPT:\n${context}`);await db.from('study_activity').insert({user_id:req.user.id,resource_id:rr.data.id,activity_type:'tutor_chat',metadata:{question}});res.json({answer})});
app.post('/api/activity',access,async(req,res)=>{let type=String(req.body.type||''),valid=['lecture_open','lecture_complete','notes_review','quiz_attempt','flashcard_review','tutor_chat','break_game'];if(!valid.includes(type))return res.status(400).json({error:'Invalid activity'});let r=await db.from('study_activity').insert({user_id:req.user.id,resource_id:req.body.resourceId||null,activity_type:type,metadata:req.body.metadata||{}}).select('id').single();res.status(r.error?400:200).json({ok:!r.error,id:r.data?.id})});
app.post('/api/quiz/attempt',access,async(req,res)=>{let total=Math.max(0,Number(req.body.total||0)),score=Math.max(0,Number(req.body.score||0)),answers=Array.isArray(req.body.answers)?req.body.answers:[];let r=await db.from('quiz_attempts').insert({user_id:req.user.id,resource_id:req.body.resourceId||null,total,score,answers}).select('id').single();if(r.error)return res.status(400).json({error:r.error.message});await db.from('study_activity').insert({user_id:req.user.id,resource_id:req.body.resourceId||null,activity_type:'quiz_attempt',metadata:{score,total}});res.json({ok:true,id:r.data.id})});
app.post('/api/notes',access,async(req,res)=>{let resourceId=req.body.resourceId,body=String(req.body.body||'');let r=await db.from('user_notes').upsert({user_id:req.user.id,resource_id:resourceId,body,updated_at:new Date().toISOString()},{onConflict:'user_id,resource_id'}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{note:r.data})});
app.get('/api/notes/:resourceId',access,async(req,res)=>{let r=await db.from('user_notes').select('*').eq('user_id',req.user.id).eq('resource_id',req.params.resourceId).maybeSingle();res.json({note:r.data||null})});
function localDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:process.env.APP_TIMEZONE||'Africa/Nairobi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function streakFromDates(dates){let set=new Set(dates),today=localDate(),d=new Date(today+'T00:00:00Z');let streak=0;for(let i=0;i<370;i++){let key=d.toISOString().slice(0,10);if(!set.has(key)){if(i===0){d.setUTCDate(d.getUTCDate()-1);continue}break}streak++;d.setUTCDate(d.getUTCDate()-1)}let longest=0,run=0,prev=null;for(const x of [...set].sort()){if(prev){let a=new Date(prev+'T00:00:00Z'),b=new Date(x+'T00:00:00Z');if((b-a)/86400000===1)run++;else run=1}else run=1;longest=Math.max(longest,run);prev=x}return {current:streak,longest}}
app.get('/api/progress',access,async(req,res)=>{let a=await db.from('study_activity').select('resource_id,activity_type,created_at,metadata').eq('user_id',req.user.id).order('created_at',{ascending:false}).limit(2000);let q=await db.from('quiz_attempts').select('resource_id,score,total,created_at').eq('user_id',req.user.id).order('created_at',{ascending:false}).limit(1000);let r=await db.from('resources').select('id,title,topic');let acts=a.data||[],qs=q.data||[],dates=[...new Set(acts.filter(x=>['lecture_open','lecture_complete','notes_review','quiz_attempt','flashcard_review','break_game'].includes(x.activity_type)).map(x=>new Date(x.created_at).toLocaleDateString('en-CA',{timeZone:process.env.APP_TIMEZONE||'Africa/Nairobi'})))];let st=streakFromDates(dates),completed=new Set(acts.filter(x=>x.activity_type==='lecture_complete').map(x=>x.resource_id)).size,totalQ=qs.reduce((n,x)=>n+(x.total||0),0),correct=qs.reduce((n,x)=>n+(x.score||0),0);let recent=acts.slice(0,12);res.json({streak:st,lecturesCompleted:completed,quizAnswered:totalQ,accuracy:totalQ?Math.round(correct/totalQ*100):0,activityCount:acts.length,recent,resources:r.data||[]})});
app.post('/api/games/score',access,async(req,res)=>{let game=String(req.body.game||'').slice(0,40),score=Math.max(0,Math.floor(Number(req.body.score||0))),duration=Math.max(1,Math.floor(Number(req.body.duration||60)));if(!game)return res.status(400).json({error:'Game required'});let r=await db.from('game_scores').insert({user_id:req.user.id,game,score,duration_seconds:duration}).select('*').single();await db.from('study_activity').insert({user_id:req.user.id,activity_type:'break_game',metadata:{game,score,duration}});res.status(r.error?400:200).json(r.error?{error:r.error.message}:{score:r.data})});
app.get('/api/games/scores',access,async(req,res)=>{let r=await db.from('game_scores').select('game,score,duration_seconds,created_at').eq('user_id',req.user.id).order('score',{ascending:false}).limit(20);res.json({scores:r.data||[]})});
async function ensureAdmin(){let e=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase(),p=String(process.env.ADMIN_PASSWORD||'');if(!e||!p)return;let q=await db.from('app_users').select('id').eq('email',e).maybeSingle();let h=await bcrypt.hash(p,12);if(q.data)await db.from('app_users').update({password_hash:h,role:'developer',subscription_status:'active'}).eq('id',q.data.id);else await db.from('app_users').insert({email:e,password_hash:h,role:'developer',subscription_status:'active'})}
app.use((q,s)=>s.sendFile(path.join(__dirname,'public','index.html')));
Promise.all([ensureAdmin(),ensureStorage()]).finally(()=>app.listen(Number(process.env.PORT||3000),()=>console.log('MedStudy running')));
