require('dotenv').config();
const express=require('express'),cookieParser=require('cookie-parser'),jwt=require('jsonwebtoken'),bcrypt=require('bcryptjs'),path=require('path');
const {createClient}=require('@supabase/supabase-js');
const crypto=require('crypto');
const app=express();
app.use(express.json({limit:'60mb'})); app.use(cookieParser()); app.use(express.static('public'));
const db=createClient(process.env.SUPABASE_URL,process.env.SUPABASE_SERVICE_ROLE_KEY,{auth:{autoRefreshToken:false,persistSession:false}});
const SECRET=process.env.JWT_SECRET, PRICE=Number(process.env.SUBSCRIPTION_PRICE||600), PAYNO=process.env.PAYMENT_NUMBER||'0736501740';
const AI_KEY=process.env.OPENAI_API_KEY||'', AI_MODEL=process.env.OPENAI_MODEL||'gpt-5.6-luna';
const phone=v=>String(v||'').replace(/\s+/g,'').replace(/^\+254/,'0');
const safe=u=>({id:u.id,email:u.email,phone:u.phone,role:u.role,subscription_status:u.subscription_status,created_at:u.created_at});
function session(res,u){res.cookie('medstudy_session',jwt.sign({sub:u.id,role:u.role},SECRET,{expiresIn:'7d'}),{httpOnly:true,secure:process.env.NODE_ENV==='production',sameSite:'lax',maxAge:604800000});}
async function user(req){try{let t=req.cookies.medstudy_session;if(!t)return null;let p=jwt.verify(t,SECRET);let {data}=await db.from('app_users').select('id,email,phone,role,subscription_status,created_at').eq('id',p.sub).single();return data||null}catch{return null}}
const auth=async(req,res,next)=>{req.user=await user(req);if(!req.user)return res.status(401).json({error:'Sign in required'});next()};
const access=async(req,res,next)=>{req.user=await user(req);if(!req.user)return res.status(401).json({error:'Sign in required'});if(req.user.role!=='developer'&&req.user.subscription_status!=='active')return res.status(402).json({error:'Active KSh 600 subscription required'});next()};
const admin=async(req,res,next)=>{req.user=await user(req);if(!req.user||req.user.role!=='developer')return res.status(403).json({error:'Developer access only'});next()};
app.get('/api/config',(q,s)=>s.json({price:PRICE,paymentNumber:PAYNO,aiConfigured:!!AI_KEY}));
app.post('/api/auth/signup',async(req,res)=>{let email=String(req.body.email||'').trim().toLowerCase()||null,ph=phone(req.body.phone)||null,p=String(req.body.password||'');if(!email&&!ph)return res.status(400).json({error:'Email or phone required'});if(p.length<8)return res.status(400).json({error:'Password must be at least 8 characters'});let filters=[];if(email)filters.push('email.eq.'+email);if(ph)filters.push('phone.eq.'+ph);let q=await db.from('app_users').select('id').or(filters.join(','));if(q.data&&q.data.length)return res.status(409).json({error:'Account already exists'});let h=await bcrypt.hash(p,12),r=await db.from('app_users').insert({email,phone:ph,password_hash:h}).select('id,email,phone,role,subscription_status,created_at').single();if(r.error)return res.status(500).json({error:r.error.message});session(res,r.data);res.json({user:r.data})});
app.post('/api/auth/login',async(req,res)=>{let id=String(req.body.identity||'').trim(),em=id.toLowerCase(),ph=phone(id),filters=['email.eq.'+em,'phone.eq.'+ph],q=await db.from('app_users').select('*').or(filters.join(',')).limit(1).maybeSingle();if(q.error||!q.data||!(await bcrypt.compare(String(req.body.password||''),q.data.password_hash)))return res.status(401).json({error:'Incorrect sign-in details'});session(res,q.data);res.json({user:safe(q.data)})});
app.post('/api/auth/logout',(q,s)=>{s.clearCookie('medstudy_session');s.json({ok:true})});
app.get('/api/me',async(q,s)=>s.json({user:await user(q)}));
app.get('/api/topics',async(q,s)=>{let r=await db.from('anatomy_topics').select('*').order('sort_order');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{topics:r.data})});
app.get('/api/subjects',async(q,s)=>{let r=await db.from('subjects').select('*').order('sort_order').order('name');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{subjects:r.data})});
app.get('/api/subjects/:id/topics',async(q,s)=>{let r=await db.from('subject_topics').select('*').eq('subject_id',q.params.id).order('sort_order').order('name');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{topics:r.data})});
app.get('/api/books',access,async(q,s)=>{let r=await db.from('book_references').select('*').order('title');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{books:r.data})});

app.get('/api/resources',access,async(q,s)=>{let r=await db.from('resources').select('*').order('subject').order('topic').order('created_at');s.status(r.error?500:200).json(r.error?{error:r.error.message}:{resources:r.data})});
app.get('/api/resources/:id',access,async(req,res)=>{let r=await db.from('resources').select('*').eq('id',req.params.id).single();if(r.error)return res.status(404).json({error:'Lecture not found'});res.json({resource:r.data})});
app.post('/api/payments',auth,async(req,res)=>{if(req.user.role==='developer')return res.json({status:'active'});let code=String(req.body.mpesaCode||'').trim().toUpperCase();if(!/^[A-Z0-9]{8,20}$/.test(code))return res.status(400).json({error:'Enter your M-Pesa transaction code'});let x=await db.from('payments').select('id').eq('mpesa_code',code).maybeSingle();if(x.data)return res.status(409).json({error:'Code already submitted'});let r=await db.from('payments').insert({user_id:req.user.id,amount:PRICE,payment_number:PAYNO,mpesa_code:code}).select('id,status').single();if(r.error)return res.status(500).json({error:r.error.message});await db.from('app_users').update({subscription_status:'pending'}).eq('id',req.user.id);res.json({payment:r.data})});
app.get('/api/admin/payments',admin,async(q,s)=>{let r=await db.from('payments').select('id,user_id,amount,payment_number,mpesa_code,status,created_at,verified_at,verified_by').order('created_at',{ascending:false});if(r.error)return s.status(500).json({error:r.error.message});let ids=[...new Set((r.data||[]).map(x=>x.user_id).filter(Boolean))];let users=ids.length?await db.from('app_users').select('id,email,phone').in('id',ids):{data:[],error:null};if(users.error)return s.status(500).json({error:users.error.message});let byId=Object.fromEntries((users.data||[]).map(u=>[u.id,{email:u.email,phone:u.phone}]));s.json({payments:(r.data||[]).map(x=>({...x,app_users:byId[x.user_id]||null}))})});
app.post('/api/admin/payments/:id/:action',admin,async(req,res)=>{let action=req.params.action;if(!['approve','reject'].includes(action))return res.status(400).json({error:'Invalid action'});let p=await db.from('payments').select('*').eq('id',req.params.id).single();if(p.error)return res.status(404).json({error:'Payment not found'});await db.from('payments').update({status:action==='approve'?'approved':'rejected',verified_at:new Date().toISOString(),verified_by:req.user.id}).eq('id',p.data.id);await db.from('app_users').update({subscription_status:action==='approve'?'active':'locked'}).eq('id',p.data.user_id);res.json({ok:true})});
app.post('/api/admin/subjects',admin,async(req,res)=>{let name=String(req.body.name||'').trim(),description=String(req.body.description||'').trim();if(!name)return res.status(400).json({error:'Subject name required'});let r=await db.from('subjects').insert({name,description}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{subject:r.data})});
app.post('/api/admin/subjects/:id/topics',admin,async(req,res)=>{let name=String(req.body.name||'').trim();if(!name)return res.status(400).json({error:'Topic name required'});let r=await db.from('subject_topics').insert({subject_id:req.params.id,name}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{topic:r.data})});
app.post('/api/admin/books',admin,async(req,res)=>{let b=req.body,title=String(b.title||'').trim(),url=String(b.url||'').trim();if(!title||!url)return res.status(400).json({error:'Book title and URL are required'});let r=await db.from('book_references').insert({title,authors:String(b.authors||'').trim()||null,edition:String(b.edition||'').trim()||null,url,notes:String(b.notes||'').trim()||null,subject_id:b.subject_id||null,topic_id:b.topic_id||null,created_by:req.user.id}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{book:r.data})});
app.post('/api/admin/topics',admin,async(req,res)=>{let name=String(req.body.name||'').trim(),group=String(req.body.group_name||'General anatomy').trim();if(!name)return res.status(400).json({error:'Name required'});let r=await db.from('anatomy_topics').insert({name,group_name:group}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{topic:r.data})});
app.post('/api/admin/resources',admin,async(req,res)=>{let b=req.body,title=String(b.title||'').trim(),url=String(b.url||'').trim();if(!title||!url)return res.status(400).json({error:'Title and URL are required'});let r=await db.from('resources').insert({kind:b.kind||'video',title,subject:String(b.subject||'Anatomy').trim(),topic:String(b.topic||'General anatomy').trim(),url,page:b.page||null,created_by:req.user.id}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{resource:r.data})});
async function ensureStorage(){try{let x=await db.storage.getBucket('medstudy-resources');if(x.error){await db.storage.createBucket('medstudy-resources',{public:false,fileSizeLimit:'40MB',allowedMimeTypes:['application/pdf','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.oasis.opendocument.presentation','text/plain','audio/mpeg','audio/mp4','audio/wav','audio/x-m4a']})}}catch(e){console.error('Storage setup:',e.message)}}
function safeName(v){return String(v||'file').replace(/[^a-zA-Z0-9._-]+/g,'_').slice(0,120)}
app.post('/api/admin/resources/upload',admin,async(req,res)=>{let b=req.body,title=String(b.title||'').trim(),mime=String(b.mimeType||''),base=String(b.fileBase64||'').replace(/^data:[^,]+,/,'');if(!title||!mime||!base)return res.status(400).json({error:'Title, file type and file are required'});let allowed=['application/pdf','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/vnd.oasis.opendocument.presentation'];if(!allowed.includes(mime))return res.status(400).json({error:'Only PDF, PPT, PPTX or ODP lecture files are supported'});let buf;try{buf=Buffer.from(base,'base64')}catch{return res.status(400).json({error:'Invalid file data'})}if(buf.length>40*1024*1024)return res.status(413).json({error:'File is too large. Maximum is 40 MB on this setup.'});let sid=b.subject_id||null,tid=b.topic_id||null,sub= sid?await db.from('subjects').select('name').eq('id',sid).single():{data:null},top=tid?await db.from('subject_topics').select('name').eq('id',tid).single():{data:null};let resource=await db.from('resources').insert({kind:'slides',title,subject:sub.data?.name||String(b.subject||'General'),topic:top.data?.name||String(b.topic||'General'),subject_id:sid,topic_id:tid,description:String(b.description||'').trim()||null,created_by:req.user.id}).select('*').single();if(resource.error)return res.status(400).json({error:resource.error.message});let pathKey='resources/'+resource.data.id+'/'+crypto.randomUUID()+'-'+safeName(b.fileName||'lecture.pdf');let up=await db.storage.from('medstudy-resources').upload(pathKey,buf,{contentType:mime,upsert:false});if(up.error){await db.from('resources').delete().eq('id',resource.data.id);return res.status(400).json({error:up.error.message})}let rf=await db.from('resource_files').insert({resource_id:resource.data.id,subject_id:sid,topic_id:tid,title,storage_path:pathKey,mime_type:mime,size_bytes:buf.length,created_by:req.user.id}).select('*').single();if(rf.error){await db.storage.from('medstudy-resources').remove([pathKey]);await db.from('resources').delete().eq('id',resource.data.id);return res.status(400).json({error:rf.error.message})}res.json({resource:resource.data,file:rf.data})});
app.get('/api/resources/:id/file-url',access,async(req,res)=>{let f=await db.from('resource_files').select('*').eq('resource_id',req.params.id).maybeSingle();if(f.error||!f.data)return res.status(404).json({error:'File not found'});let u=await db.storage.from('medstudy-resources').createSignedUrl(f.data.storage_path,3600);if(u.error)return res.status(500).json({error:u.error.message});res.json({url:u.data.signedUrl,file:f.data})});
function youtubeId(url){try{let u=new URL(url);if(u.hostname==='youtu.be')return u.pathname.slice(1);if(u.hostname.includes('youtube.com')){if(u.pathname.startsWith('/embed/'))return u.pathname.split('/')[2];if(u.pathname.startsWith('/shorts/'))return u.pathname.split('/')[2];return u.searchParams.get('v')}}catch{}return null}
async function fetchTranscript(url){let id=youtubeId(url);if(!id)throw Error('This lecture does not have a supported YouTube video URL.');try{const mod=await import('youtube-transcript-plus');const result=await mod.fetchTranscript(id);let text=result.map(x=>x.text).join(' ').replace(/\s+/g,' ').trim();if(!text)throw Error('No transcript was returned.');return {text,language:'en'};}catch(e){throw Error('Could not fetch a YouTube transcript. The video may have captions disabled, or YouTube may be blocking transcript requests from the server. You can add a transcript manually from the developer dashboard.');}}
function extractText(data){if(typeof data==='string')return data;let out=[];function walk(x){if(!x)return;if(typeof x==='string')out.push(x);else if(Array.isArray(x))x.forEach(walk);else if(typeof x==='object'){if(typeof x.text==='string')out.push(x.text);else Object.values(x).forEach(walk)}}walk(data);return out.join('\n').trim()}
async function ai(prompt){if(!AI_KEY)throw Error('AI is not configured yet. Add OPENAI_API_KEY to the Railway service variables.');let r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{'Content-Type':'application/json','Authorization':'Bearer '+AI_KEY},body:JSON.stringify({model:AI_MODEL,input:prompt})});let d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error?.message||'AI request failed');let t=extractText(d.output||d);if(!t)throw Error('AI returned an empty response');return t;}
function cleanJson(t){let x=t.trim().replace(/^\`\`\`(?:json)?/i,'').replace(/\`\`\`$/,'').trim();let a=x.indexOf('{'),b=x.lastIndexOf('}');if(a>=0&&b>a)return x.slice(a,b+1);a=x.indexOf('[');b=x.lastIndexOf(']');if(a>=0&&b>a)return x.slice(a,b+1);return x;}
async function getTranscriptFor(resource,allowManual=true){let c=await db.from('lecture_transcripts').select('*').eq('resource_id',resource.id).maybeSingle();if(c.data)return c.data;if(!allowManual)throw Error('No transcript available for this lecture.');if(resource.kind==='slides'){let f=await db.from('resource_files').select('*').eq('resource_id',resource.id).maybeSingle();if(f.data&&f.data.mime_type==='application/pdf'){let file=await db.storage.from('medstudy-resources').download(f.data.storage_path);if(!file.error){try{const pdfParse=(await import('pdf-parse')).default;let parsed=await pdfParse(file.data);if(parsed.text?.trim()){let r=await db.from('lecture_transcripts').insert({resource_id:resource.id,source:'uploaded-pdf',language:'en',transcript:parsed.text}).select('*').single();if(r.error)throw Error(r.error.message);return r.data}}catch(e){throw Error('The PDF was uploaded, but its text could not be extracted: '+e.message)}}}}let tr=await fetchTranscript(resource.url);let r=await db.from('lecture_transcripts').insert({resource_id:resource.id,source:'youtube',language:tr.language,transcript:tr.text}).select('*').single();if(r.error)throw Error(r.error.message);return r.data}
function splitText(text,size=42000){let words=text.split(/\s+/),chunks=[],cur='';for(const w of words){if((cur+' '+w).trim().length>size){chunks.push(cur.trim());cur=w}else cur=(cur+' '+w).trim()}if(cur)chunks.push(cur);return chunks.slice(0,5)}
async function generatePack(resource,transcript){let chunks=splitText(transcript,42000),summaries=[];for(let i=0;i<chunks.length;i++){summaries.push(await ai(`You are an anatomy education assistant. Summarize ONLY the source transcript below. Do not invent facts not supported by it. Preserve anatomical terminology. Produce concise study notes with headings, structures, relations, actions, innervation, blood supply, clinical points, and must-remember facts where the transcript actually covers them.\n\nSOURCE CHUNK ${i+1}/${chunks.length}:\n${chunks[i]}`))}
let combined=summaries.join('\n\n--- CHUNK SUMMARY ---\n');let prompt=`Create a complete study pack for the anatomy lecture titled "${resource.title}". The material below is derived from the lecture transcript. Stay grounded in it and clearly avoid adding unsupported details. Return VALID JSON only with this shape: {"overview":"","objectives":[""],"notes":[{"heading":"","points":[""]}],"key_structures":[""],"clinical_correlations":[""],"must_remember":[""],"summary":"","questions":[{"type":"mcq","question":"","options":["","","",""],"answer":0,"explanation":""}],"flashcards":[{"front":"","back":""}]}. Make 10 useful MCQs, 12 flashcards, and comprehensive notes.\n\nLECTURE MATERIAL:\n${combined}`;let raw=await ai(prompt),pack=JSON.parse(cleanJson(raw));return pack}
app.post('/api/resources/:id/ai/generate',access,async(req,res)=>{let rr=await db.from('resources').select('*').eq('id',req.params.id).single();if(rr.error)return res.status(404).json({error:'Lecture not found'});try{let tr=await getTranscriptFor(rr.data),pack=await generatePack(rr.data,tr.transcript);let old=await db.from('ai_study_packs').select('id').eq('resource_id',rr.data.id).maybeSingle();let r=old.data?await db.from('ai_study_packs').update({notes:pack,questions:pack.questions||[],flashcards:pack.flashcards||[],model:AI_MODEL,updated_at:new Date().toISOString()}).eq('resource_id',rr.data.id).select('*').single():await db.from('ai_study_packs').insert({resource_id:rr.data.id,notes:pack,questions:pack.questions||[],flashcards:pack.flashcards||[],model:AI_MODEL}).select('*').single();if(r.error)throw Error(r.error.message);res.json({pack:r.data})}catch(e){res.status(400).json({error:e.message})}});
app.get('/api/resources/:id/ai',access,async(req,res)=>{let r=await db.from('ai_study_packs').select('*').eq('resource_id',req.params.id).maybeSingle();res.json({pack:r.data||null})});
app.post('/api/resources/:id/transcript',admin,async(req,res)=>{let text=String(req.body.transcript||'').trim();if(text.length<50)return res.status(400).json({error:'Transcript is too short'});let r=await db.from('lecture_transcripts').upsert({resource_id:req.params.id,source:'manual',language:String(req.body.language||'en'),transcript:text,updated_at:new Date().toISOString()},{onConflict:'resource_id'}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{transcript:r.data})});
app.post('/api/resources/:id/tutor',access,async(req,res)=>{let rr=await db.from('resources').select('*').eq('id',req.params.id).single();if(rr.error)return res.status(404).json({error:'Lecture not found'});let tr=await getTranscriptFor(rr.data),question=String(req.body.question||'').trim();if(!question)return res.status(400).json({error:'Ask a question first'});let context=tr.transcript.slice(0,60000);let answer=await ai(`You are a source-grounded anatomy tutor. Answer the student's question using ONLY the lecture transcript below. If the transcript does not support the answer, say that it is not covered in this lecture. Explain clearly at medical-student level and do not fabricate.\n\nQUESTION:\n${question}\n\nLECTURE TRANSCRIPT:\n${context}`);await db.from('study_activity').insert({user_id:req.user.id,resource_id:rr.data.id,activity_type:'tutor_chat',metadata:{question}});res.json({answer})});
app.post('/api/activity',access,async(req,res)=>{let type=String(req.body.type||''),valid=['lecture_open','lecture_complete','notes_review','quiz_attempt','flashcard_review','tutor_chat','break_game'];if(!valid.includes(type))return res.status(400).json({error:'Invalid activity'});let r=await db.from('study_activity').insert({user_id:req.user.id,resource_id:req.body.resourceId||null,activity_type:type,metadata:req.body.metadata||{}}).select('id').single();res.status(r.error?400:200).json({ok:!r.error,id:r.data?.id})});
app.post('/api/quiz/attempt',access,async(req,res)=>{let total=Math.max(0,Number(req.body.total||0)),score=Math.max(0,Number(req.body.score||0)),answers=Array.isArray(req.body.answers)?req.body.answers:[];let r=await db.from('quiz_attempts').insert({user_id:req.user.id,resource_id:req.body.resourceId||null,total,score,answers}).select('id').single();if(r.error)return res.status(400).json({error:r.error.message});await db.from('study_activity').insert({user_id:req.user.id,resource_id:req.body.resourceId||null,activity_type:'quiz_attempt',metadata:{score,total}});res.json({ok:true,id:r.data.id})});
app.post('/api/notes',access,async(req,res)=>{let resourceId=req.body.resourceId,body=String(req.body.body||'');let r=await db.from('user_notes').upsert({user_id:req.user.id,resource_id:resourceId,body,updated_at:new Date().toISOString()},{onConflict:'user_id,resource_id'}).select('*').single();res.status(r.error?400:200).json(r.error?{error:r.error.message}:{note:r.data})});
app.get('/api/notes/:resourceId',access,async(req,res)=>{let r=await db.from('user_notes').select('*').eq('user_id',req.user.id).eq('resource_id',req.params.resourceId).maybeSingle();res.json({note:r.data||null})});
function localDate(){return new Intl.DateTimeFormat('en-CA',{timeZone:process.env.APP_TIMEZONE||'Africa/Nairobi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function streakFromDates(dates){let set=new Set(dates),today=localDate(),d=new Date(today+'T00:00:00Z');let streak=0;for(let i=0;i<370;i++){let key=d.toISOString().slice(0,10);if(!set.has(key)){if(i===0){d.setUTCDate(d.getUTCDate()-1);continue}break}streak++;d.setUTCDate(d.getUTCDate()-1)}let longest=0,run=0,prev=null;for(const x of [...set].sort()){if(prev){let a=new Date(prev+'T00:00:00Z'),b=new Date(x+'T00:00:00Z');if((b-a)/86400000===1)run++;else run=1}else run=1;longest=Math.max(longest,run);prev=x}return {current:streak,longest}}
app.get('/api/progress',access,async(req,res)=>{let a=await db.from('study_activity').select('resource_id,activity_type,created_at,metadata').eq('user_id',req.user.id).order('created_at',{ascending:false}).limit(2000);let q=await db.from('quiz_attempts').select('resource_id,score,total,created_at').eq('user_id',req.user.id).order('created_at',{ascending:false}).limit(1000);let r=await db.from('resources').select('id,title,topic');let acts=a.data||[],qs=q.data||[],dates=[...new Set(acts.filter(x=>['lecture_open','lecture_complete','notes_review','quiz_attempt','flashcard_review','break_game'].includes(x.activity_type)).map(x=>new Date(x.created_at).toLocaleDateString('en-CA',{timeZone:process.env.APP_TIMEZONE||'Africa/Nairobi'})))];let st=streakFromDates(dates),completed=new Set(acts.filter(x=>x.activity_type==='lecture_complete').map(x=>x.resource_id)).size,totalQ=qs.reduce((n,x)=>n+(x.total||0),0),correct=qs.reduce((n,x)=>n+(x.score||0),0);let recent=acts.slice(0,12);res.json({streak:st,lecturesCompleted:completed,quizAnswered:totalQ,accuracy:totalQ?Math.round(correct/totalQ*100):0,activityCount:acts.length,recent,resources:r.data||[]})});
app.post('/api/games/score',access,async(req,res)=>{let game=String(req.body.game||'').slice(0,40),score=Math.max(0,Math.floor(Number(req.body.score||0))),duration=Math.max(1,Math.floor(Number(req.body.duration||60)));if(!game)return res.status(400).json({error:'Game required'});let r=await db.from('game_scores').insert({user_id:req.user.id,game,score,duration_seconds:duration}).select('*').single();await db.from('study_activity').insert({user_id:req.user.id,activity_type:'break_game',metadata:{game,score,duration}});res.status(r.error?400:200).json(r.error?{error:r.error.message}:{score:r.data})});
app.get('/api/games/scores',access,async(req,res)=>{let r=await db.from('game_scores').select('game,score,duration_seconds,created_at').eq('user_id',req.user.id).order('score',{ascending:false}).limit(20);res.json({scores:r.data||[]})});
async function ensureAdmin(){let e=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase(),p=String(process.env.ADMIN_PASSWORD||'');if(!e||!p)return;let q=await db.from('app_users').select('id').eq('email',e).maybeSingle();let h=await bcrypt.hash(p,12);if(q.data)await db.from('app_users').update({password_hash:h,role:'developer',subscription_status:'active'}).eq('id',q.data.id);else await db.from('app_users').insert({email:e,password_hash:h,role:'developer',subscription_status:'active'})}
app.use((q,s)=>s.sendFile(path.join(__dirname,'public','index.html')));
Promise.all([ensureAdmin(),ensureStorage()]).finally(()=>app.listen(Number(process.env.PORT||3000),()=>console.log('MedStudy running')));
